{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-fragment",
    "version": "2.7.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.slidingpanelayout",
          "module": "slidingpanelayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.7.7.aar",
          "url": "navigation-fragment-2.7.7.aar",
          "size": 94370,
          "sha512": "a84266742da20de0e79c1c994fb19d4b11943b8b1c0b6aa9fa88ea145f40589bae9f15b9fcedd1f9151555b5ef9039656bfa87766633e73abba1ad4ce03243b1",
          "sha256": "e63c7d2edb636390b322455457787e07043148dcda5dd37866d21f02d455df4b",
          "sha1": "5e68a5069f1176a1afb34e9e3d95b4d7e54deb60",
          "md5": "d55446d489186bbf042ddd8c8698b1d2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.slidingpanelayout",
          "module": "slidingpanelayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.7.7.aar",
          "url": "navigation-fragment-2.7.7.aar",
          "size": 94370,
          "sha512": "a84266742da20de0e79c1c994fb19d4b11943b8b1c0b6aa9fa88ea145f40589bae9f15b9fcedd1f9151555b5ef9039656bfa87766633e73abba1ad4ce03243b1",
          "sha256": "e63c7d2edb636390b322455457787e07043148dcda5dd37866d21f02d455df4b",
          "sha1": "5e68a5069f1176a1afb34e9e3d95b4d7e54deb60",
          "md5": "d55446d489186bbf042ddd8c8698b1d2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.7.7-sources.jar",
          "url": "navigation-fragment-2.7.7-sources.jar",
          "size": 27493,
          "sha512": "bb500172eaee6dea56a90c39f22eccc1b3fd34b6dad6637464658d902b876d28e5c83c693a8053dfd50231f18030d9bb1b3f1b0cce64861daec140a3562bd01d",
          "sha256": "0829d271fa2890fcd219619a06fed16f55d93838293604306036c65f468d2698",
          "sha1": "125aa820ec810c1d518e40fc607870af788d5cd7",
          "md5": "a4c9672c2653139ad551529c793c9092"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.7"
          },
          "reason": "navigation-fragment is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.7.7-versionMetadata.json",
          "url": "navigation-fragment-2.7.7-versionMetadata.json",
          "size": 12989,
          "sha512": "f08b6f0763ef6c3c7b704787b4d6f813cdcbdb21a6e6ccfb629fbdff56c54a526657a709ecca60d0fbdb19b9013110917a03db56425e7e507a2790d4f0fcc823",
          "sha256": "b56f987ae12e1ffbf41fcef6b06911933584616e0cb8c4e6d299f6dee075e503",
          "sha1": "28380087e2222d3f5d7b46394b59dc3615e01190",
          "md5": "ab6b892b627aeefc013457edf378534d"
        }
      ]
    }
  ]
}